require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.4
  Exclude:
    - 'Rakefile'
    - 'Guardfile'
    - 'bin/*'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config/initializers/action_view/helpers/translation_helper.rb'
    - 'cookbooks/**/*'
    - 'db/migrate/*'
    - 'db/archived_migrations/*'
    - 'db/schema.rb'
    - 'odd jobs/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'test/**/*'
  DisplayCopNames: true
  NewCops: enable

Rails:
  Enabled: true

Style/Alias:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Style/AsciiComments:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/GuardClause:
  MinBodyLength: 5

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_inspect

Style/ClassAndModuleChildren:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/SymbolArray:
  Enabled: false
  EnforcedStyle: percent

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/WordArray:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Enabled: false

Lint/ToEnumArguments:
  Enabled: false

Lint/UnmodifiedReduceAccumulator:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/CollectionCompact:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/NegatedIfElseCondition:
  Enabled: false

Style/NilLambda:
  Enabled: false

Style/SwapValues:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Lint/Debugger:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Lint/UnreachableLoop:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/RedundantSelfAssignment:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Rails/ActiveRecordCallbacksOrder:
  Enabled: false

Rails/AfterCommitOverride:
  Enabled: false

Rails/FindById:
  Enabled: false

Rails/Inquiry:
  Enabled: false

Rails/MailerName:
  Enabled: false

Rails/MatchRoute:
  Enabled: false

Rails/NegateInclude:
  Enabled: false

Rails/Pluck:
  Enabled: false

Rails/PluckInWhere:
  Enabled: false

Rails/RenderInline:
  Enabled: false

Rails/RenderPlainText:
  Enabled: false

Rails/ShortI18n:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/WhereExists:
  Enabled: false

Rails/WhereNot:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/ReadWriteAttribute:
  Enabled: false

Rails/EnumHash:
  Enabled: false

Rails/RedundantForeignKey:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false
